// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RendEx - Descubra sua renda extra ideal",
  description: "Teste rápido para descobrir qual renda extra combina com seu perfil",
  icons: {
    icon: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/a82c7fc2-5610-443e-9cd2-db5315a16124.png",
    shortcut: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/a82c7fc2-5610-443e-9cd2-db5315a16124.png",
    apple: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/a82c7fc2-5610-443e-9cd2-db5315a16124.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
